In [ ]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [65]:
##import dataset

In [66]:
df_heart_d=pd.read_csv('Dataset_csv/heart_disease_data.csv')

In [67]:
df_heart_d.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [68]:
##column in dataset
df_heart_d.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [69]:
df_heart_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [70]:
df_heart_d.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [71]:
## in this dataset missing values are not present 

In [72]:
## mean,std,statistical data
df_heart_d.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [73]:
##our target is to find the heart is healthy or defective

In [74]:
df_heart_d['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [75]:
## 1 ----> Unhealty heart
## 0 ----> healthy heart

In [76]:
##now split data in independent and dependent

In [77]:
X=df_heart_d.drop('target',axis=1)
y=df_heart_d['target']

In [78]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [79]:
type(y),type(X)

(pandas.core.series.Series, pandas.core.frame.DataFrame)

In [80]:
X.shape,y.shape

((303, 13), (303,))

In [81]:
## we need to Normalize the data
sc=StandardScaler()

In [82]:
sc.fit(X)

StandardScaler()

In [83]:
X_scaled=sc.fit_transform(X)

In [84]:
X_scaled

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -2.27457861,
        -0.71442887, -2.14887271],
       [-1.91531289,  0.68100522,  1.00257707, ..., -2.27457861,
        -0.71442887, -0.51292188],
       [-1.47415758, -1.46841752,  0.03203122, ...,  0.97635214,
        -0.71442887, -0.51292188],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ..., -0.64911323,
         1.24459328,  1.12302895],
       [ 0.29046364,  0.68100522, -0.93851463, ..., -0.64911323,
         0.26508221,  1.12302895],
       [ 0.29046364, -1.46841752,  0.03203122, ..., -0.64911323,
         0.26508221, -0.51292188]])

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [90]:
X_train.shape,y_train.shape

((242, 13), (242,))

In [91]:
 ## dataset is small so we can use Support Vector Machine

In [92]:
from sklearn.svm import SVC




In [93]:
# Train SVM model (with scaled data)
svm_model = SVC(kernel="rbf", random_state=42)
svm_model.fit(X_train, y_train)

SVC(random_state=42)

In [94]:
# Make predictions
y_pred_svm = svm_model.predict(X_test)


In [98]:
from sklearn.metrics import classification_report,confusion_matrix

In [99]:
# Evaluate SVM model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
class_report_svm = classification_report(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)

In [100]:
accuracy_svm, class_report_svm, conf_matrix_svm

(0.7049180327868853,
 '              precision    recall  f1-score   support\n\n           0       0.79      0.52      0.62        29\n           1       0.67      0.88      0.76        32\n\n    accuracy                           0.70        61\n   macro avg       0.73      0.70      0.69        61\nweighted avg       0.73      0.70      0.69        61\n',
 array([[15, 14],
        [ 4, 28]], dtype=int64))

In [101]:
print("accuracy_score is")
accuracy_svm

accuracy_score is


0.7049180327868853

In [104]:
print("classification_report is")
print(class_report_svm)

classification_report is
              precision    recall  f1-score   support

           0       0.79      0.52      0.62        29
           1       0.67      0.88      0.76        32

    accuracy                           0.70        61
   macro avg       0.73      0.70      0.69        61
weighted avg       0.73      0.70      0.69        61



In [106]:
print("confusion_matrix is")
print(conf_matrix_svm)

confusion_matrix is
[[15 14]
 [ 4 28]]


In [107]:
model = LogisticRegression()

In [108]:
model.fit(X_train,y_train)

C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [109]:
pred=model.predict(X_test)

In [114]:
# Evaluate SVM model
accuracy_sv = accuracy_score(y_test, pred)
class_report_sv = classification_report(y_test, y_pred_svm)
conf_matrix_sv = confusion_matrix(y_test, y_pred_svm)

In [115]:
print("classification_report is")
print(class_report_sv)

classification_report is
              precision    recall  f1-score   support

           0       0.79      0.52      0.62        29
           1       0.67      0.88      0.76        32

    accuracy                           0.70        61
   macro avg       0.73      0.70      0.69        61
weighted avg       0.73      0.70      0.69        61



In [116]:
print("confusion_matrix is")
print(conf_matrix_sv)

confusion_matrix is
[[15 14]
 [ 4 28]]


In [117]:
print("accuracy_score is")
accuracy_sv

accuracy_score is


0.8852459016393442

In [118]:
import pickle

# Save the model
with open("heart_disease_model.pkl", "wb") as file:
    pickle.dump(model, file)

In [119]:
# Load the model later
with open("heart_disease_model.pkl", "rb") as file:
    loaded_model = pickle.load(file)

# Test with new data
predictions = loaded_model.predict(X_test)

In [120]:
input_data = (57,0,0,120,354,0,1,163,1,0.6,2,0,2)

# change the input data to a numpy array
input_data_as_numpy_array= np.asarray(input_data)
print(input_data_as_numpy_array.dtype)

# reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
print(input_data_reshaped.dtype)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]== 0):
  print('The Person does not have a Heart Disease')
else:
  print('The Person has Heart Disease')

float64
float64
[1]
The Person has Heart Disease


C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
